name: CI - Go POC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      run: go build -o my-go-app ./...

    - name: Run Unit Tests & Coverage
      run: |
        go test -v -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.out

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-go-app-binary
        path: ./my-go-app

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install and Run SonarScanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli-5.0.1.3006-linux.zip
        ./sonar-scanner-5.0.1.3006/bin/sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} -X -Dsonar.verbose=true

  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .

