name: CI - Go POC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      run: go build -o my-go-app ./...

    - name: Run Unit Tests & Coverage
      run: |
        go test -v -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.out

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-go-app-binary
        path: ./my-go-app

    - name: SonarCloud Analysis
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        organization: sumitchh
        projectKey: sumitchh_my-go-app_1
        token: ${{ secrets.SONAR_TOKEN }}

  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .

